export const COPY = {
  zh: {
    eyebrow: "本机内容 · 原件索引",
    title: "本地资料库",
    description: "快速查找文章、邮件、任务及输入输出文件。这里只维护原件引用，不重复保存文件。",
    search: "搜索本地资料",
    searchPlaceholder: "搜索标题、邮件发件人、文件名或正文…",
    kind: "内容类型",
    project: "项目范围",
    relatedTask: "关联任务",
    sourceType: "资料来源",
    month: "时间目录",
    availability: "原件状态",
    indexState: "索引状态",
    allKinds: "全部类型",
    allProjects: "全部项目",
    allTasks: "全部任务",
    allSources: "全部来源",
    allMonths: "全部时间",
    allAvailability: "全部原件状态",
    allIndexStates: "全部索引状态",
    kinds: { article: "文章", mail: "邮件", task: "任务", task_input: "任务输入", task_output: "任务输出" },
    available: "原件可用",
    unavailable: "原件不可用",
    metadataOnly: "仅元数据",
    partial: "内容索引不完整",
    missing: "原件缺失",
    ready: "全文可检索",
    addToTask: "添加到任务",
    preview: "安全预览",
    previewTitle: "安全全文预览",
    previewSafety: "以纯文本显示；不会执行 HTML、脚本，也不会加载远程图片或其他资源。",
    previewLoading: "正在验证并读取原件…",
    previewUnsupported: "此格式暂不支持安全全文预览，可以在文件管理器中定位原件。",
    previewNeedsOcr: "PDF 中没有足够的可提取文字，暂时需要 OCR；可以先定位原件查看。",
    previewTooLarge: "文件超过安全解析上限，请在文件管理器中定位原件查看。",
    previewExtractionFailed: "文档文字抽取失败，原件没有改变；可以定位原件或刷新索引后重试。",
    previewFailed: "无法预览：原件可能已移动、变化或暂时不可读。请刷新索引后重试。",
    previewTruncated: "抽取内容已按安全上限截断（原文件 {{size}}）。",
    locate: "定位原件",
    locating: "正在定位…",
    located: "已在文件管理器中定位“{{name}}”。",
    locateFailed: "暂时无法在文件管理器中定位原件，请确认文件仍在原位置。",
    chooseTask: "添加资料引用",
    chooseTaskHint: "这里只给任务记录原件引用；AI 启动任务时才会创建受控工作副本。",
    task: "目标任务",
    chooseTaskPlaceholder: "选择一个未完成任务",
    noTasks: "当前范围内没有可添加资料的未完成任务。",
    loadingTasks: "正在读取可用任务…",
    add: "确认添加",
    cancel: "取消",
    close: "关闭",
    adding: "正在添加…",
    added: "已添加到“{{task}}”。原件位置未改变。",
    openTask: "打开任务",
    addFailed: "暂时无法添加。任务或原件可能刚刚发生变化，请刷新后重试。",
    changed: "原件已发生变化，请刷新资料库后重新选择。",
    originalMissing: "原件当前不可用，不能添加到任务。",
    empty: "本地资料库还没有索引内容",
    emptyHint: "建立索引后，已下载文章、归档邮件、任务及其输入输出会显示在这里。不会移动或复制原件。",
    noMatches: "没有匹配的本地资料",
    noMatchesHint: "请尝试更短的关键词、其他内容类型或全部项目。",
    build: "建立索引",
    refresh: "刷新索引",
    rebuilding: "正在更新索引…",
    autoIndexing: "检测到本机内容变化，正在自动更新索引…",
    autoIndexFailed: "自动索引上次未完成。现有索引仍可使用，可执行完整刷新进行修复。",
    indexed: "已索引 {{count}} 项 · {{available}} 项原件可用",
    lastIndexed: "上次更新 {{time}}",
    loadFailed: "暂时无法读取本地资料库；本机原件没有受到影响。",
    rebuildFailed: "索引更新失败；现有索引和原件均未改变。",
    retry: "重试",
    previous: "上一页",
    next: "下一页",
    page: "第 {{page}} 页",
    source: "来源",
    related: "关联",
    sameOriginal: "同一原件 · {{count}} 个使用位置",
  },
  en: {
    eyebrow: "On-device content · original index",
    title: "Local library",
    description: "Find articles, mail, tasks, inputs, and outputs. The library indexes originals without storing duplicate files.",
    search: "Search local content",
    searchPlaceholder: "Search titles, senders, filenames, or text…",
    kind: "Content type",
    project: "Project scope",
    relatedTask: "Related task",
    sourceType: "Source",
    month: "Date directory",
    availability: "Original status",
    indexState: "Index status",
    allKinds: "All types",
    allProjects: "All projects",
    allTasks: "All tasks",
    allSources: "All sources",
    allMonths: "All dates",
    allAvailability: "All original states",
    allIndexStates: "All index states",
    kinds: { article: "Article", mail: "Mail", task: "Task", task_input: "Task input", task_output: "Task output" },
    available: "Original available",
    unavailable: "Original unavailable",
    metadataOnly: "Metadata only",
    partial: "Partial content index",
    missing: "Original missing",
    ready: "Full text searchable",
    addToTask: "Add to task",
    preview: "Safe preview",
    previewTitle: "Safe full-text preview",
    previewSafety: "Shown as plain text. HTML and scripts are not executed, and remote images or other resources are not loaded.",
    previewLoading: "Verifying and reading the original…",
    previewUnsupported: "This format does not support a safe full-text preview yet. You can locate the original in the file manager.",
    previewNeedsOcr: "The PDF does not contain enough extractable text and currently needs OCR. You can locate the original instead.",
    previewTooLarge: "The file exceeds the safe parsing limit. Locate the original to view it.",
    previewExtractionFailed: "Text extraction failed without changing the original. Locate it or refresh the index and try again.",
    previewFailed: "The original could not be previewed. It may have moved, changed, or become unreadable; refresh the index and try again.",
    previewTruncated: "Extracted text was truncated at the safety limit (original file {{size}}).",
    locate: "Locate original",
    locating: "Locating…",
    located: "Located “{{name}}” in the file manager.",
    locateFailed: "The original could not be located in the file manager. Confirm that it remains in its original location.",
    chooseTask: "Add content reference",
    chooseTaskHint: "This records a reference to the original. AI creates a controlled working copy only when the task starts.",
    task: "Target task",
    chooseTaskPlaceholder: "Choose an unfinished task",
    noTasks: "No unfinished task in this scope can accept this content.",
    loadingTasks: "Loading available tasks…",
    add: "Add reference",
    cancel: "Cancel",
    close: "Close",
    adding: "Adding…",
    added: "Added to “{{task}}”. The original was not moved.",
    openTask: "Open task",
    addFailed: "Could not add the reference. The task or original may have changed; refresh and try again.",
    changed: "The original changed. Refresh the library and select it again.",
    originalMissing: "The original is unavailable and cannot be added to a task.",
    empty: "The local library has not been indexed yet",
    emptyHint: "Build the index to find downloaded articles, archived mail, tasks, inputs, and outputs. Originals are never moved or copied.",
    noMatches: "No matching local content",
    noMatchesHint: "Try a shorter query, another content type, or all projects.",
    build: "Build index",
    refresh: "Refresh index",
    rebuilding: "Updating index…",
    autoIndexing: "A local content change was detected. Updating the index automatically…",
    autoIndexFailed: "The last automatic index update did not finish. The existing index remains usable; run a full refresh to repair it.",
    indexed: "{{count}} indexed · {{available}} originals available",
    lastIndexed: "Last updated {{time}}",
    loadFailed: "The local library could not be read. Originals on this computer were not affected.",
    rebuildFailed: "The index could not be updated. The existing index and originals were unchanged.",
    retry: "Try again",
    previous: "Previous",
    next: "Next",
    page: "Page {{page}}",
    source: "Source",
    related: "Related",
    sameOriginal: "Same original · {{count}} contexts",
  },
} as const;

export type LocalLibraryCopy = (typeof COPY)[keyof typeof COPY];
