export function buildPublicState({
  namespace,
  protocolVersion,
  state,
  currentProject,
  defaultAgent,
  loopRoutineReadModel,
  codexApprovalQueue,
  evidenceCenterRecords,
}) {
  return {
    namespace,
    protocolVersion,
    device: state.device,
    projects: state.projects,
    currentProjectId: state.currentProjectId,
    currentProject: currentProject(),
    loopRoutines: loopRoutineReadModel(),
    worktrees: state.worktrees,
    agent: defaultAgent(),
    agents: state.agents,
    invocations: state.invocations,
    compareRuns: state.compareRuns,
    events: state.events,
    traces: state.traces,
    spans: state.spans,
    auditSummaries: state.auditSummaries,
    healthChecks: state.healthChecks,
    lifecycleAuditRecords: state.lifecycleAuditRecords,
    discoveryRuns: state.discoveryRuns,
    integrationArtifacts: state.integrationArtifacts,
    integrationProbeRuns: state.integrationProbeRuns,
    quotaDecisionRecords: state.quotaDecisionRecords,
    retentionSettings: state.retentionSettings,
    approvalRequests: state.approvalRequests,
    policyDecisionRecords: state.policyDecisionRecords,
    troubleshootingReports: state.troubleshootingReports,
    agentUsageSummaries: state.agentUsageSummaries,
    codexSessions: state.codexSessions,
    codexWorkspaces: state.codexWorkspaces,
    codexEvidenceRecords: state.codexEvidenceRecords,
    codexChangeReviews: state.codexChangeReviews,
    codexHookEvents: state.codexHookEvents,
    codexApprovalQueue: codexApprovalQueue(),
    evidenceCenterRecords: evidenceCenterRecords(),
    codexApprovalBrokerRequests: state.codexApprovalBrokerRequests,
    codexImportedEvidenceRecords: state.codexImportedEvidenceRecords,
    terminalRuntimeCapability: state.terminalRuntimeCapability,
    terminalSessions: state.terminalSessions,
    terminalEvidenceRecords: state.terminalEvidenceRecords,
    terminalBridgeActions: state.terminalBridgeActions,
    sshTargets: state.sshTargets,
    sshConnectionTests: state.sshConnectionTests,
  };
}
