import { i18n } from "@/lib/i18n";

export const channelTranslations = {
  "en-US": {
    channelsPage: { messaging: "Messaging", title: "Channels", description: "Connect WeChat ClawBot or another messaging channel. Credentials stay local; the console shows readiness and health, never secrets.", empty: "No channels registered", emptyHint: "Connect a messaging channel to create governed tasks from your messages.", approveHint: "Allow /approve from inside this channel. Off by default; risky runs are approved separately in the console.", inChannelApprove: "in-channel /approve", disable: "Disable", enable: "Enable", ready: "ready", missing: "missing", taskProject: "Task project", noneDisabled: "none (/task disabled)", autoRoute: "auto-route", day: "day", today: "today", save: "Save", capture: "capture", unbound: "unbound — /task refused", tasks: "Channel tasks", route: "Route", dismiss: "Dismiss", retry: "Retry", reroute: "Reroute", takeover: "Take over", addWechat: "Connect WeChat ClawBot", channelName: "Channel name", channelNamePlaceholder: "My WeChat", connect: "Connect", connecting: "Connecting…", scanTitle: "Scan with WeChat", scanHint: "Open WeChat and scan this code to authorize ClawBot.", waitingScan: "Waiting for scan…", scanned: "Scanned — confirming…", authenticated: "Authorized", activate: "Start receiving messages", pairTitle: "Bind your WeChat account", pairHint: "Send this exact message to ClawBot in WeChat:", pairWaiting: "Waiting for the binding message…", pairDone: "WeChat is connected", pairCode: "Binding code", reconnect: "Reconnect", disconnect: "Disconnect", copy: "Copy", copyDone: "Copied", qrUnavailable: "The QR code could not be loaded.", setupFailed: "WeChat setup failed. Try again.", providerWechat: "WeChat ClawBot", interactions: "Interaction records", viewInteractions: "View interaction records", hideInteractions: "Hide interaction records", interactionEmpty: "No interaction records yet", interactionLoading: "Loading records…", interactionLoadFailed: "Could not load interaction records.", allDirections: "All directions", allTypes: "All message types", allStatuses: "All statuses", inbound: "Inbound", outbound: "Outbound", text: "Text", image: "Image", voice: "Voice", file: "File", mixed: "Mixed", searchInteractions: "Search messages or files", showingInteractions: "Showing {{count}} records", loadMore: "Load more", flagged: "Prompt-injection warning", attachment: "Attachment", noContent: "No text content", delivered: "Delivered", queued: "Queued", sending: "Sending", retrying: "Retrying", failedTerminal: "Failed" },
  },
  "zh-CN": {
    channelsPage: { messaging: "消息", title: "频道", description: "连接微信 ClawBot 或其他消息渠道。凭据保留在本机；控制台只显示就绪和健康状态，不显示密钥。", empty: "尚未注册频道", emptyHint: "连接消息渠道，即可从微信消息创建受治理的任务。", approveHint: "允许在频道内使用 /approve。默认关闭；高风险运行由另一位操作员在控制台审批。", inChannelApprove: "频道内 /approve", disable: "禁用", enable: "启用", ready: "就绪", missing: "缺失", taskProject: "任务项目", noneDisabled: "无（/task 已禁用）", autoRoute: "自动路由", day: "天", today: "今天", save: "保存", capture: "仅捕获", unbound: "未绑定 — /task 已拒绝", tasks: "频道任务", route: "路由", dismiss: "忽略", retry: "重试", reroute: "重新路由", takeover: "接管", addWechat: "连接微信 ClawBot", channelName: "渠道名称", channelNamePlaceholder: "我的微信", connect: "连接", connecting: "连接中…", scanTitle: "用微信扫码", scanHint: "打开微信扫描此二维码，授权 ClawBot。", waitingScan: "等待扫码…", scanned: "已扫码，确认中…", authenticated: "已授权", activate: "开始接收消息", pairTitle: "绑定你的微信账号", pairHint: "在微信中向 ClawBot 发送以下完整消息：", pairWaiting: "等待绑定消息…", pairDone: "微信已连接", pairCode: "绑定口令", reconnect: "重新连接", disconnect: "断开连接", copy: "复制", copyDone: "已复制", qrUnavailable: "二维码加载失败。", setupFailed: "微信设置失败，请重试。", providerWechat: "微信 ClawBot", interactions: "交互记录", viewInteractions: "查看交互记录", hideInteractions: "收起交互记录", interactionEmpty: "暂无交互记录", interactionLoading: "正在加载记录…", interactionLoadFailed: "交互记录加载失败。", allDirections: "全部方向", allTypes: "全部消息类型", allStatuses: "全部状态", inbound: "入站", outbound: "出站", text: "文本", image: "图片", voice: "语音", file: "文件", mixed: "混合", searchInteractions: "搜索消息或文件", showingInteractions: "显示 {{count}} 条记录", loadMore: "加载更多", flagged: "提示注入风险", attachment: "附件", noContent: "无文本内容", delivered: "已送达", queued: "排队中", sending: "发送中", retrying: "重试中", failedTerminal: "发送失败" },
  },
} as const;

let installed = false;

export function installChannelTranslations() {
  if (installed) return;
  installed = true;
  for (const [locale, translation] of Object.entries(channelTranslations)) {
    i18n.addResourceBundle(locale, "common", translation, true, true);
  }
}
