export const resources = {
  "en-US": {
    common: {
      sectionGroups: { work: "Work", run: "Run", oversee: "Oversee", configure: "Configure", ledgers: "Ledgers" },
      sections: {
        dashboard: { label: "Overview", blurb: "Start a task and watch it run" }, workBoard: { label: "Status", blurb: "Every work item by state" },
        workspace: { label: "Workspace", blurb: "Project files, transcript, and history in one place" }, documents: { label: "Documents", blurb: "Browse Word, Excel, PowerPoint, and PDF files" }, canvas: { label: "Canvas", blurb: "Draw and edit diagrams and Excalidraw scenes" },
        autoRuns: { label: "Auto-runs", blurb: "Autonomous issue to worktree to PR runs" }, task: { label: "Task", blurb: "GitHub issues and PRs as work items" }, compare: { label: "Compare", blurb: "Run one task on multiple agents side by side" }, automation: { label: "Automation", blurb: "Rules that run agents on a trigger" }, routines: { label: "Routines", blurb: "Scheduled autonomous checks and findings" },
        approvals: { label: "Approvals", blurb: "Every pending human decision in one queue" }, evidence: { label: "Evidence", blurb: "Per-run review, audit, and troubleshooting" }, review: { label: "Review", blurb: "Codex and Claude diff-review findings" }, evalTrend: { label: "Capability", blurb: "Real-agent evaluation trends and regressions" }, audit: { label: "Audit", blurb: "What was recorded and why" },
        projects: { label: "Projects", blurb: "Group work and own budgets" }, agents: { label: "Agents", blurb: "Registered agents and health" }, agentSkills: { label: "Agent Skills", blurb: "Instruction docs rendered into agent runs" }, devices: { label: "Devices", blurb: "Local bridges and platforms" }, discovery: { label: "Discovery", blurb: "Find local agents conservatively" }, integrations: { label: "Integrations", blurb: "Connect unsupported agents" }, tools: { label: "Tools", blurb: "Governed tools you can discover and run" }, applications: { label: "Applications", blurb: "Registered apps and governed capabilities" }, channels: { label: "Channels", blurb: "Messaging channels and their deliveries" },
        invocations: { label: "Invocations", blurb: "Every call, status, and result" }, economics: { label: "Economics", blurb: "Metered AI usage and cost ledger" },
      },
      shell: {
        controlPlane: "Control plane", navLabel: "Control plane sections", footer: "Register agents, route calls, enforce permission, and record what happened.",
        project: "Project", currentProject: "Current project", section: "Section", connected: "Connected", connecting: "Connecting", offline: "Server offline", deviceOnline: "Online and ready", deviceOffline: "Offline", deviceUnknown: "Unknown",
        pending: "{{count}} pending", attention: "{{count}} need attention", registerProject: "Register a project", close: "Close",
        command: { label: "Command palette", placeholder: "Jump to a section…", search: "Search sections", sections: "Sections", noMatch: "No section matches “{{query}}”.", navigate: "navigate", open: "open", toggle: "toggle" },
        skin: { label: "Skin", mode: "Theme mode", default: "Indigo (default)", ocean: "Ocean", ink: "Graphite", light: "Light", dark: "Dark", system: "System" },
      },
      shared: { confirm: "Confirm", cancel: "Cancel", working: "Working…", governedConfirmation: "This action is governed and requires explicit confirmation.", errorTitle: "This view hit an error", errorBody: "The rest of the console still works — switch sections from the sidebar, or try again.", tryAgain: "Try again" },
      login: { signIn: "Sign in", signOut: "Sign out", userId: "User id", password: "Password", signingIn: "Signing in…", failed: "Sign in failed." },
      inspector: { label: "Context inspector", bridgeTitle: "Local Agent Bridge", bridgeBody: "The cloud can request local work, but the bridge owns final execution. Start Desktop Bridge to bring this device online.", discoveryTitle: "Conservative by design", discoveryBody: "Discovery checks only known or user-provided sources and never enables a candidate automatically.", reviewTitle: "Findings, not raw output", reviewBody: "Review findings are structured, non-authoritative output. Raw model transcripts and CLI output stay server-side.", economicsTitle: "One economic ledger", economicsBody: "Agent cost, AI usage, chargeback, and settlement roll up through one ledger." },
      dashboard: {
        defaultTask: "Summarize the local demo state and confirm the bridge is working.", activity: "Activity", composerTitle: "What should your computer do?", task: "Task", project: "Project", agent: "Agent", noProject: "No project", noAgent: "No agent registered",
        continueSession: "Continuing session", startFresh: "Start fresh", runningIn: "Running in worktree {{branch}}", projectDefault: "Use project default", queue: "Queue for this computer", run: "Run on this computer", cancel: "Cancel task", details: "Technical details",
        safety: "Safety", data: "Data", cost: "Cost", cancellation: "Cancellation", computer: "Computer", adapter: "Adapter", lifecycle: "Lifecycle", taskId: "Task ID", trace: "Trace", state: "State", noTask: "No task yet", noTrace: "No trace yet", noDelivery: "no delivery",
        reviewAgent: "Review the selected agent before running.", recorded: "Task input and result are recorded.",
        block: { offline: "Server is offline.", task: "Enter a task before running.", agent: "Select an agent before running.", disabled: "{{name}} is disabled. Enable it before running a new task.", unhealthy: "{{name}} is unhealthy. Run a health check after fixing it.", running: "Wait for the current task to finish or cancel it." },
        gettingStarted: "Getting started", go: "Go →", device: "Link a local device", deviceOnline: "Device online", deviceDetail: "The local bridge runs your agents", registerProject: "Register a project", projects_one: "{{count}} project", projects_other: "{{count}} projects", projectDetail: "Clone or link a repo to work in", readyAgent: "Have a ready agent", agentReady: "An agent is ready", agentDetail: "An agent executes your tasks", firstTask: "Run your first task", runs_one: "{{count}} run", runs_other: "{{count}} runs", taskDetail: "Use the composer below",
      },
      workBoard: {
        title: "Status", items: "{{count}} items", subtitle: "Every work item by state · newest first", emptyTitle: "Nothing tracked yet", emptyHint: "Auto-runs, pending decisions, and recent refusals land here, grouped by state.", none: "None", more: "+{{count}} more",
        lens: { pending_decision: "Pending decision", follow_up: "Follow-up", in_progress: "In progress", waiting: "Waiting", failed: "Failed", done: "Done" },
        schedule: "Schedule to channel", on: "on", off: "off", next: "next {{time}}", last: "last {{time}}", close: "Close", configure: "Configure", noChannels: "No channels registered — add a WeCom channel first.", noConversations: "No conversations yet — someone must message the bot before reports can be posted.", enabled: "Enabled", channel: "Channel", to: "To", report: "Report", cover: "Cover", cadence: "Cadence", day: "Day", time: "Time", pick: "— pick —", previous: "last period", current: "this period", daily: "daily", weekly: "weekly", save: "Save", postNow: "Post now", postTitle: "Send the configured report to the channel now", posted_one: "Posted ({{count}} message)", posted_other: "Posted ({{count}} messages)", notPosted: "Not posted: {{reason}}", serverTime: "Time is server-local; posts once per period.",
        period: { day: "day", week: "week", month: "month", quarter: "quarter" }, since: "since {{date}}", copyTitle: "Copy this period's Markdown report", copied: "Copied", copy: "Copy report", opened: "Opened", completed: "Completed", failed: "Failed", refusals: "Refusals", refusalsPartial: "Refusals*", refusalHint: "Lower bound — the durable rollup started after this window's start", aging: "Aging >24h",
      },
      workspace: { noProjects: "No projects yet", noProjectsHint: "Register a local project to browse its files and run tasks against it.", register: "Register a project", project: "Project", noRegistered: "No projects registered", select: "Select a project…", selectHint: "Register or select a project to start.", notGit: "not a Git repository", preview: "Office preview", previewHint: "click a .docx / .xlsx / .pptx in the file tree, or enter a path", files: "Project files", transcript: "Agent transcript", history: "Session history", officeLabel: "OfficeCLI preview", path: "Document path, e.g. deck.pptx", render: "Render", supported: "Preview supports .docx, .xlsx, and .pptx.", rendering: "rendering…", unavailable: "Preview unavailable.", empty: "Enter a document path and Render to preview it here (rendered by OfficeCLI, read-only)." },
      cad: { inspecting: "Inspecting CAD drawing…", details: "Drawing details", version: "Version", units: "Units code", entities: "Entities", audit: "Audit: {{errors}} errors, {{fixes}} fixes", layers: "Layers", warnings: "Fidelity warnings", layout: "CAD layout", zoomOut: "Zoom out", zoomIn: "Zoom in", fit: "Fit", searchLabel: "Search CAD text", searchPlaceholder: "Search annotations", noMatches: "No matching drawing text.", rendering: "Rendering layout…", frameTitle: "CAD layout {{layout}}", unavailable: "CAD preview unavailable", failure: { oda: "DWG preview requires an approved, operator-installed ODA File Converter. DXF preview remains available.", ezdxf: "The local ezdxf preview runtime is unavailable or unhealthy.", tooLarge: "This drawing exceeds the local preview safety limits.", invalid: "This {{type}} file is invalid, corrupt, or does not match its extension.", generic: "The CAD drawing could not be previewed safely." } },
      pdf: { controls: "PDF controls", hideThumbnails: "Hide thumbnails", showThumbnails: "Show thumbnails", previousPage: "Previous page", pageNumber: "Page number", nextPage: "Next page", zoomOut: "Zoom out", zoomIn: "Zoom in", fit: "Fit", fitWidth: "Fit width", rotate: "Rotate clockwise", download: "Download PDF", print: "Print PDF", fullscreen: "Enter fullscreen", hideDetails: "Hide PDF details", showDetails: "Show PDF details", searchLabel: "Search PDF text", searchPlaceholder: "Search PDF…", searching: "Searching…", find: "Find", next: "Next", results: "0 results", pageRange: "Enter a page from 1 to {{count}}.", unlockLabel: "Unlock PDF", password: "PDF password", unlock: "Unlock", cancel: "Cancel", incorrectPassword: "Incorrect password. Try again.", protected: "This PDF is password protected.", passwordCancelled: "Password entry was cancelled. You can retry when ready.", passwordPrivacy: "The password is used only in memory and is not stored.", details: "PDF details", local: "Local PDF", pages: "{{count}} pages", notRegistered: "not registered", validate: "Validate", readMetadata: "Read metadata", validation: "Validation", metadataInspection: "Metadata inspection", queued: "queued", thumbnails: "PDF thumbnails", preview: "PDF preview {{path}}", loading: "Loading PDF…", unavailable: "PDF preview unavailable", tryAgain: "Try again", pageCanvas: "Page {{page}} of {{count}}", selectableText: "Selectable text for page {{page}}", goToPage: "Go to page {{page}}", metadata: { version: "PDF version", Title: "Title", Author: "Author", Subject: "Subject", Creator: "Creator", Producer: "Producer" }, error: { canvas: "Canvas rendering is unavailable in this browser.", render: "PDF page rendering failed.", unauthorized: "Your session cannot access this PDF. Sign in again and retry.", tooLarge: "This PDF exceeds the local preview size limit.", missing: "The PDF no longer exists at this project path.", invalid: "This file is malformed or is not a supported PDF.", timeout: "PDF loading timed out. Check the local runtime and retry.", range: "The local PDF service returned an invalid range response. Retry or restart the local service.", password: "The PDF password was not accepted. Retry with the correct password.", generic: "PDF preview failed.", toolUnavailable: "pdfcpu is unavailable on this device. Install or restart the local runtime, then retry.", toolTimeout: "PDF {{action}} timed out. Check pdfcpu readiness and retry.", toolUnauthorized: "Your session is not authorized to inspect this PDF.", toolFailed: "PDF {{action}} failed." } },
      languagePicker: {
        label: "Language",
        english: "English",
        simplifiedChinese: "Simplified Chinese",
      },
    },
  },
  "zh-CN": {
    common: {
      sectionGroups: { work: "工作", run: "运行", oversee: "监督", configure: "配置", ledgers: "台账" },
      sections: {
        dashboard: { label: "概览", blurb: "启动任务并查看运行过程" }, workBoard: { label: "状态", blurb: "按状态查看所有工作项" },
        workspace: { label: "工作区", blurb: "集中查看项目文件、记录与历史" }, documents: { label: "文档", blurb: "浏览 Word、Excel、PowerPoint 和 PDF 文件" }, canvas: { label: "画布", blurb: "绘制和编辑图表及 Excalidraw 场景" },
        autoRuns: { label: "自动运行", blurb: "从 Issue 到工作树和 PR 的自主运行" }, task: { label: "任务", blurb: "将 GitHub Issue 和 PR 作为工作项" }, compare: { label: "对比", blurb: "让多个 Agent 并行执行同一任务" }, automation: { label: "自动化", blurb: "由触发器运行 Agent 的规则" }, routines: { label: "例行任务", blurb: "定时自主检查及其发现" },
        approvals: { label: "审批", blurb: "集中处理所有待人工决策" }, evidence: { label: "证据", blurb: "每次运行的评审、审计与排障" }, review: { label: "评审", blurb: "Codex 和 Claude 的差异评审发现" }, evalTrend: { label: "能力", blurb: "真实 Agent 的评测趋势与回归" }, audit: { label: "审计", blurb: "记录了什么以及为什么" },
        projects: { label: "项目", blurb: "组织工作并管理预算" }, agents: { label: "Agent", blurb: "已注册 Agent 及其健康状态" }, agentSkills: { label: "Agent 技能", blurb: "用于 Agent 运行的指令文档" }, devices: { label: "设备", blurb: "本地桥接与平台" }, discovery: { label: "发现", blurb: "以保守方式发现本地 Agent" }, integrations: { label: "集成", blurb: "连接尚未支持的 Agent" }, tools: { label: "工具", blurb: "可发现和运行的受治理工具" }, applications: { label: "应用", blurb: "已注册应用及受治理能力" }, channels: { label: "渠道", blurb: "消息渠道及其投递" },
        invocations: { label: "调用", blurb: "每次调用、状态与结果" }, economics: { label: "成本", blurb: "AI 用量与成本台账" },
      },
      shell: {
        controlPlane: "控制平面", navLabel: "控制平面栏目", footer: "注册 Agent、路由调用、执行权限并记录发生的一切。",
        project: "项目", currentProject: "当前项目", section: "栏目", connected: "已连接", connecting: "连接中", offline: "服务器离线", deviceOnline: "在线且就绪", deviceOffline: "离线", deviceUnknown: "未知",
        pending: "{{count}} 项待处理", attention: "{{count}} 项需关注", registerProject: "注册项目", close: "关闭",
        command: { label: "命令面板", placeholder: "跳转到栏目…", search: "搜索栏目", sections: "栏目", noMatch: "没有匹配“{{query}}”的栏目。", navigate: "导航", open: "打开", toggle: "切换" },
        skin: { label: "皮肤", mode: "主题模式", default: "靛蓝（默认）", ocean: "海洋", ink: "石墨", light: "亮色", dark: "暗色", system: "跟随系统" },
      },
      shared: { confirm: "确认", cancel: "取消", working: "处理中…", governedConfirmation: "此操作受治理，需要明确确认。", errorTitle: "此视图发生错误", errorBody: "控制台其他部分仍可使用；请从侧栏切换栏目或重试。", tryAgain: "重试" },
      login: { signIn: "登录", signOut: "退出登录", userId: "用户 ID", password: "密码", signingIn: "登录中…", failed: "登录失败。" },
      inspector: { label: "上下文检查器", bridgeTitle: "本地 Agent 桥接", bridgeBody: "云端可以请求本地工作，但最终执行由桥接程序控制。请启动桌面桥接使设备上线。", discoveryTitle: "保守发现", discoveryBody: "发现功能只检查已知或用户提供的来源，绝不会自动启用候选项。", reviewTitle: "结构化发现，而非原始输出", reviewBody: "评审发现是结构化、非权威的输出；原始模型记录和 CLI 输出保留在服务器端。", economicsTitle: "统一成本台账", economicsBody: "Agent 成本、AI 用量、分摊与结算统一汇总到一个台账。" },
      dashboard: {
        defaultTask: "总结本地演示状态，并确认桥接程序运行正常。", activity: "活动", composerTitle: "希望这台电脑做什么？", task: "任务", project: "项目", agent: "Agent", noProject: "无项目", noAgent: "尚未注册 Agent",
        continueSession: "继续会话", startFresh: "开始新会话", runningIn: "在工作树 {{branch}} 中运行", projectDefault: "使用项目默认设置", queue: "排队等待此电脑", run: "在此电脑上运行", cancel: "取消任务", details: "技术详情",
        safety: "安全", data: "数据", cost: "成本", cancellation: "取消能力", computer: "电脑", adapter: "适配器", lifecycle: "生命周期", taskId: "任务 ID", trace: "追踪", state: "状态", noTask: "尚无任务", noTrace: "尚无追踪", noDelivery: "未投递",
        reviewAgent: "运行前请检查所选 Agent。", recorded: "任务输入和结果会被记录。",
        block: { offline: "服务器离线。", task: "请先输入任务。", agent: "请先选择 Agent。", disabled: "{{name}} 已禁用，请先启用再运行新任务。", unhealthy: "{{name}} 状态异常，请修复后执行健康检查。", running: "请等待当前任务结束或将其取消。" },
        gettingStarted: "开始使用", go: "前往 →", device: "连接本地设备", deviceOnline: "设备在线", deviceDetail: "本地桥接程序负责运行 Agent", registerProject: "注册项目", projects_one: "{{count}} 个项目", projects_other: "{{count}} 个项目", projectDetail: "克隆或连接一个代码仓库", readyAgent: "准备可用的 Agent", agentReady: "Agent 已就绪", agentDetail: "Agent 会执行你的任务", firstTask: "运行第一个任务", runs_one: "{{count}} 次运行", runs_other: "{{count}} 次运行", taskDetail: "使用下方任务输入框",
      },
      workBoard: {
        title: "状态", items: "{{count}} 项", subtitle: "按状态查看所有工作项 · 最新优先", emptyTitle: "尚无跟踪项", emptyHint: "自动运行、待决策事项和最近的拒绝会按状态汇总到这里。", none: "无", more: "另有 {{count}} 项",
        lens: { pending_decision: "待决策", follow_up: "需跟进", in_progress: "进行中", waiting: "等待中", failed: "已失败", done: "已完成" },
        schedule: "定时发送到渠道", on: "开启", off: "关闭", next: "下次 {{time}}", last: "上次 {{time}}", close: "关闭", configure: "配置", noChannels: "尚未注册渠道，请先添加企业微信渠道。", noConversations: "尚无会话；需要有人先向机器人发送消息，才能投递报告。", enabled: "启用", channel: "渠道", to: "接收人", report: "报告", cover: "范围", cadence: "频率", day: "星期", time: "时间", pick: "— 选择 —", previous: "上一周期", current: "当前周期", daily: "每天", weekly: "每周", save: "保存", postNow: "立即发送", postTitle: "立即将已配置的报告发送到渠道", posted_one: "已发送（{{count}} 条消息）", posted_other: "已发送（{{count}} 条消息）", notPosted: "未发送：{{reason}}", serverTime: "时间以服务器本地时区为准；每周期仅发送一次。",
        period: { day: "日", week: "周", month: "月", quarter: "季度" }, since: "自 {{date}} 起", copyTitle: "复制本周期 Markdown 报告", copied: "已复制", copy: "复制报告", opened: "新增", completed: "完成", failed: "失败", refusals: "拒绝", refusalsPartial: "拒绝*", refusalHint: "这是下限值；持久化汇总在本时间窗口开始后才启用", aging: "超过 24 小时",
      },
      workspace: { noProjects: "尚无项目", noProjectsHint: "注册本地项目后即可浏览文件并针对项目运行任务。", register: "注册项目", project: "项目", noRegistered: "尚未注册项目", select: "选择项目…", selectHint: "请注册或选择项目后开始。", notGit: "不是 Git 仓库", preview: "Office 预览", previewHint: "在文件树中点击 .docx / .xlsx / .pptx，或输入路径", files: "项目文件", transcript: "Agent 记录", history: "会话历史", officeLabel: "OfficeCLI 预览", path: "文档路径，例如 deck.pptx", render: "渲染", supported: "预览支持 .docx、.xlsx 和 .pptx。", rendering: "渲染中…", unavailable: "预览不可用。", empty: "输入文档路径并点击“渲染”即可在此只读预览（由 OfficeCLI 渲染）。" },
      cad: { inspecting: "正在检查 CAD 图纸…", details: "图纸详情", version: "版本", units: "单位代码", entities: "实体数", audit: "审计：{{errors}} 个错误，{{fixes}} 项修复", layers: "图层", warnings: "保真度警告", layout: "CAD 布局", zoomOut: "缩小", zoomIn: "放大", fit: "适应", searchLabel: "搜索 CAD 文字", searchPlaceholder: "搜索注释", noMatches: "没有匹配的图纸文字。", rendering: "正在渲染布局…", frameTitle: "CAD 布局 {{layout}}", unavailable: "CAD 预览不可用", failure: { oda: "DWG 预览需要由运维人员安装并批准 ODA File Converter；DXF 预览仍可用。", ezdxf: "本地 ezdxf 预览运行时不可用或状态异常。", tooLarge: "此图纸超出本地预览安全限制。", invalid: "此 {{type}} 文件无效、已损坏或与扩展名不匹配。", generic: "无法安全预览该 CAD 图纸。" } },
      pdf: { controls: "PDF 控件", hideThumbnails: "隐藏缩略图", showThumbnails: "显示缩略图", previousPage: "上一页", pageNumber: "页码", nextPage: "下一页", zoomOut: "缩小", zoomIn: "放大", fit: "适应", fitWidth: "适应宽度", rotate: "顺时针旋转", download: "下载 PDF", print: "打印 PDF", fullscreen: "进入全屏", hideDetails: "隐藏 PDF 详情", showDetails: "显示 PDF 详情", searchLabel: "搜索 PDF 文字", searchPlaceholder: "搜索 PDF…", searching: "搜索中…", find: "查找", next: "下一个", results: "0 个结果", pageRange: "请输入 1 到 {{count}} 之间的页码。", unlockLabel: "解锁 PDF", password: "PDF 密码", unlock: "解锁", cancel: "取消", incorrectPassword: "密码错误，请重试。", protected: "此 PDF 受密码保护。", passwordCancelled: "已取消输入密码，准备好后可重试。", passwordPrivacy: "密码仅在内存中使用，不会存储。", details: "PDF 详情", local: "本地 PDF", pages: "{{count}} 页", notRegistered: "未注册", validate: "验证", readMetadata: "读取元数据", validation: "验证", metadataInspection: "元数据检查", queued: "已排队", thumbnails: "PDF 缩略图", preview: "PDF 预览 {{path}}", loading: "正在加载 PDF…", unavailable: "PDF 预览不可用", tryAgain: "重试", pageCanvas: "第 {{page}} 页，共 {{count}} 页", selectableText: "第 {{page}} 页的可选文字", goToPage: "跳转到第 {{page}} 页", metadata: { version: "PDF 版本", Title: "标题", Author: "作者", Subject: "主题", Creator: "创建工具", Producer: "生成工具" }, error: { canvas: "此浏览器不支持画布渲染。", render: "PDF 页面渲染失败。", unauthorized: "当前会话无权访问此 PDF，请重新登录后重试。", tooLarge: "此 PDF 超出本地预览大小限制。", missing: "项目路径中已不存在此 PDF。", invalid: "此文件格式错误或不是受支持的 PDF。", timeout: "PDF 加载超时，请检查本地运行时后重试。", range: "本地 PDF 服务返回了无效的分段响应，请重试或重启本地服务。", password: "PDF 密码未被接受，请使用正确密码重试。", generic: "PDF 预览失败。", toolUnavailable: "此设备上的 pdfcpu 不可用，请安装或重启本地运行时后重试。", toolTimeout: "PDF {{action}} 超时，请检查 pdfcpu 就绪状态后重试。", toolUnauthorized: "当前会话无权检查此 PDF。", toolFailed: "PDF {{action}} 失败。" } },
      languagePicker: {
        label: "语言",
        english: "英语",
        simplifiedChinese: "简体中文",
      },
    },
  },
} as const;

export const defaultNamespace = "common" as const;
