export const notificationCenterTranslations = {
  "en-US": {
    title: "Notifications",
    close: "Close notifications",
    triggerLabel: "Notifications: {{action}} require action, {{unread}} unread",
    actionCount: "{{count}} require action",
    unreadCount: "{{count}} unread result",
    empty: "No work needs your attention.",
    templates: "Templates ready for review",
    templatesHint: "Open My templates to check and enable them",
    templatesFailed: "Needs attention",
    templatesFailedHint: "A template could not be organized; its safe copies are retained",
    templatesUntitled: "New template",
    approvals: "Approvals",
    approvalsHint: "Safety decisions waiting for you",
    failures: "Failed runs",
    failuresHint: "Runs that need recovery",
    followUps: "Follow-ups due",
    followUpsHint: "Stakeholder work ready for progress or rescheduling",
    executionOffline: "Execution disconnected",
    executionOfflineHint: "This computer cannot receive local work",
    completions: "New results",
    completionsHint: "Completed since you last reviewed results",
    status: {
      title: "Status center",
      healthy: "Healthy",
      fallback: "Periodic refresh",
      offline: "Offline",
      server: "Server",
      computer: "Execution computer",
      updates: "Updates",
      connecting: "Connecting",
      connected: "Connected",
      online: "Online",
      unknown: "Not registered",
      realtime: "Real-time",
      periodic: "Periodic refresh",
    },
    browser: {
      titleSetting: "Browser notifications",
      privacy: "Optional. Notifications show counts only—never task text, paths, or results.",
      enable: "Enable",
      disable: "Disable",
      denied: "Blocked by browser",
      unsupported: "Unavailable",
      title: "MyAgentTool has an update",
      body: "{{count}} new status update(s). Open MyAgentTool to review.",
    },
  },
  "zh-CN": {
    title: "通知",
    close: "关闭通知",
    triggerLabel: "通知：{{action}} 项需要处理，{{unread}} 项未读",
    actionCount: "{{count}} 项需要处理",
    unreadCount: "{{count}} 项未读结果",
    empty: "当前没有需要处理的工作。",
    templates: "模板已整理，等待检查",
    templatesHint: "打开“我的模板”检查并启用",
    templatesFailed: "需要处理",
    templatesFailedHint: "有模板未能整理完成，安全副本仍然保留",
    templatesUntitled: "新模板",
    approvals: "待审批",
    approvalsHint: "等待你确认的安全决策",
    failures: "运行失败",
    failuresHint: "需要恢复的运行",
    followUps: "跟进已到期",
    followUpsHint: "需要记录进展或重新安排的关系人任务",
    executionOffline: "执行已断开",
    executionOfflineHint: "这台电脑暂时无法接收本地任务",
    completions: "新结果",
    completionsHint: "上次查看后新完成的结果",
    status: {
      title: "状态中心",
      healthy: "正常",
      fallback: "定时刷新",
      offline: "离线",
      server: "服务器",
      computer: "执行电脑",
      updates: "更新方式",
      connecting: "连接中",
      connected: "已连接",
      online: "在线",
      unknown: "未登记",
      realtime: "实时更新",
      periodic: "定时刷新",
    },
    browser: {
      titleSetting: "浏览器通知",
      privacy: "可选开启。通知仅显示数量，不包含任务文本、路径或结果。",
      enable: "开启",
      disable: "关闭",
      denied: "已被浏览器阻止",
      unsupported: "不可用",
      title: "MyAgentTool 有新动态",
      body: "有 {{count}} 项新状态，请打开 MyAgentTool 查看。",
    },
  },
} as const;

export function notificationCenterCopy(language?: string) {
  return notificationCenterTranslations[language?.startsWith("zh") ? "zh-CN" : "en-US"];
}

export function formatNotificationCopy(value: string, variables: Record<string, number>) {
  return Object.entries(variables).reduce(
    (result, [key, replacement]) => result.replaceAll(`{{${key}}}`, String(replacement)),
    value,
  );
}
